### ISSUE TITLE
How do I use pagination with this gem?

### ISSUE THREAD

**Issue by bwiggs** [brightcove-archive/ooyala_ruby-v2-sdk#1]
I'm pulling back a large amount of data, and can see a next_page property in the json response from the Ooyala service. 

Does the gem facilitate grabbing paginated result sets at this time, or do I need to handle those?

**Comment by vidalon** [comment]
You need to handle that on your own. We just provide methods to do GET, PUT, PATCH, POST and DELETE requests.

**Comment by bwiggs** [comment]
@vidalon ok, thanks for the quick response.

**Comment by vidalon** [comment]
No problem.

**Comment by bwiggs** [comment]
I'm still having problems with this. When I make a successful first request, I see a `next_page` property in the response. If I try to request this url, without any additional processing, the api responds that I need to pass the api_key and a signature. So I parse the `next_param` property and pass it into this SDK's GET method, but this always results in a 400 bad signature. 

Here's the code I'm using:

```
results = ooyala_client.get("assets", parameters)
next_page = URI.parse results['next_page']
params = CGI::parse(next_page.query)
results = ooyala_client.get(next_page.path, params) # returns 400
```

Any ideas on why the signature would be invalid? Happy to provide as much information as needed.

**Comment by Pepegasca** [comment]
You need to convert the value params to string because when you use CGI::parse the values for each params are arrays.
Try to do something like this before get the next page:

```
params.each {|key, value| params[key] = value[0] )  }
```

**Comment by bwiggs** [comment]
This worked, thanks!
