### ISSUE TITLE
rest-client dependency is out of date

### ISSUE THREAD

**Issue by twelvelabs** [brightcove-archive/ooyala_ruby-v2-sdk#3]
[rest-client](https://github.com/rest-client/rest-client) is now at 1.7.2. Since the ooyala API is [locked to ~> 1.6.6](https://github.com/ooyala/ruby-v2-sdk/blob/master/gem-ooyala-v2-api/ooyala-v2-api.gemspec#L43) I can't update. Can y'all please verify that the api client works with the newer version of rest-client and relax the version dependency in the gem spec?

**Comment by twelvelabs** [comment]
Bump. /cc @Pepegasca

**Comment by Pepegasca** [comment]
We will check and update the gemfile if the new version works properly. Thanks

**Comment by Pepegasca** [comment]
Hi @twelvelabs, you can safely update the rest-client Gemfile.
