### ISSUE TITLE
Unable to request video stream data

### ISSUE THREAD

**Issue by sqlninja** [brightcove-archive/ooyala_ruby-v2-sdk#7]
Trying to retrieve stream information for my videos using this
`streams = @ooyala_api.get("/assets/#{video.embed_code}/streams")`

But it just returns:
`Ooyala::RequestErrorException: 400 Bad Request: {"message":"Invalid signature."}`

Although this works fine in the sandbox.

**Comment by AlvaroSenorale** [comment]
Hi @sqlninja!. I'm getting same error. Did you resolve this?
